on:
  push:
    branches:
      - master
    paths:
      - config.json

jobs:
  sync-config:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/github-script@0.8.0
        with:
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          script: |
            const fs = require('fs').promises

            const config = JSON.parse(await fs.readFile('./config.json'))

            await github.users.updateAuthenticated(config.user)
